package com.dam.kairos.utils;

import java.util.Arrays;
import java.util.List;

public class PromptStyles {
    public static final List<ImageStylePrompt> STYLES = Arrays.asList(
            new ImageStylePrompt("Realism", "A high-resolution photorealistic image of the followong diary entry: ", ". Analise the text to and reflect the emotions of the author in the picture."),
            new ImageStylePrompt("8-bit Pixel Art", "8-bit pixel art illustration, colorful style, detailed scene with sharp pixel blocks and retro video game aesthetics of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Cyberpunk", "Cyberpunk cityscape at night reflecting the mood of the following diary entry: ", ". Neon lights, rainy streets, holograms, and futuristic buildings should represent the writer's emotions. The atmosphere should match the emotional tone: melancholic, tense, or hopeful"),
            new ImageStylePrompt("Children's Watercolor", "A cheerful watercolor illustration of a frog wearing a tiny raincoat, jumping into a puddle surrounded by mushrooms and flowers, soft pastel colors, hand-drawn style, children's book illustration, white background, concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Dreamcore Surreal", "Dreamcore aesthetic surreal illustration inspired by the emotional depth of this diary entry: ", ". Soft pastels, liminal spaces, floating objects, and dreamlike visuals to evoke feelings like isolation, wonder, or longing."),
            new ImageStylePrompt("Synthwave Mood", "Synthwave-style digital art visualizing the emotional narrative of this diary entry: ", ". Use bold purples, pinks, and blues with a sunset horizon, glowing gridlines, and symbolic shapes that mirror the feeling of the text."),
            new ImageStylePrompt("Fantasy", "A high-resolution digital painting of a floating medieval castle surrounded by golden clouds during sunset, with winged dragons flying around it, in a dramatic cinematic lighting style, hyper-detailed architecture, fantasy concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Scifi future", "Cyberpunk city skyline at night with neon signs and flying cars, viewed from a high rooftop, in a photorealistic style, cinematic perspective, glowing reflections on wet streets, inspired by Blade Runner concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Isometric lowPoly world", "An isometric low-poly 3D forest scene with geometric trees, a small river, and a wooden cabin, vibrant color palette, stylized and minimalist design, perfect lighting, similar to a mobile game aesthetic concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Historical", "An 18th-century ballroom full of dancing nobles in period costumes, painted in the style of a classical oil painting, Baroque lighting and color palette, soft brush strokes, ornate architectural details, dramatic composition concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Futuristic mech desing", "Highly detailed concept art of a futuristic combat mech standing in a desert, surrounded by dust clouds and war debris, in a realistic style with complex mechanical parts, military sci-fi mood, hard shadows, of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Surreal dreamscape", "A surreal dream-like desert made of blue ice, with giant melting clocks hanging from translucent trees, Dali-inspired, vibrant surrealism with sharp contrast between cold and warm tones, dream logic concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Food photography", "Top-down view of a traditional Japanese ramen bowl with steam rising, rich textures of noodles, egg, pork, and green onions, shallow depth of field, high-resolution food photography lighting, on a rustic wooden table, of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Space fantasy comic", "A retro comic book-style illustration of an astronaut riding a space whale through a colorful nebula, with bold outlines, halftone shading, saturated vintage colors, and dynamic motion lines, 1980s pulp sci-fi vibe, concept art of the next prompt based on an emotional diary: ", null),
            new ImageStylePrompt("Dreamcore Surreal Landscape", "Dreamcore aesthetic surreal illustration inspired by the emotional depth of this diary entry: ", ". Soft pastels, liminal spaces, floating objects, and dreamlike visuals to evoke feelings like isolation, wonder, or longing."),
            new ImageStylePrompt("Retro Futurism", "Retro-futuristic scene with emotional undertones inspired by this diary entry: ", ". 1980s sci-fi aesthetic with glowing grids, chrome textures, distant planets, and a mood that reflects the internal state of the narrator."),
            new ImageStylePrompt("Synthwave Moodscape", "Synthwave-style digital art visualizing the emotional narrative of this diary entry: ", ". Use bold purples, pinks, and blues with a sunset horizon, glowing gridlines, and symbolic shapes that mirror the feeling of the text."),
            new ImageStylePrompt("Vintage Storybook", "Whimsical vintage storybook-style illustration based on the emotional content of this diary entry: ", ". Include gentle brush textures, muted warm tones, and imaginative symbolism (like animals, weather, or cozy rooms) to reflect the inner world."),
            new ImageStylePrompt("VHS Glitchcore", "A glitchcore / VHS-style digital composition visualizing the emotional instability or fragmentation in this diary entry: ", ". Incorporate visual distortions, scanlines, noise effects, and analog color palettes to reflect inner chaos or nostalgia."),
            new ImageStylePrompt("Noir Cinematic", "Film noir-inspired cinematic image reflecting the emotional atmosphere of this diary entry: ", ". Use high contrast lighting, grayscale tones with selective color, rain-soaked streets or smoky rooms to express emotional weight and introspection.")
    );
}
